# Copyright 2020-2026 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Golden tests: ``BaseClientConfig`` serialization behaves as it did under ``dataclasses-json``.

``tests/fixtures/base_client_config_golden.json`` was generated by THIS module's ``__main__`` block
while ``BaseClientConfig`` was still decorated with ``@dataclass_json`` (dataclasses-json 0.6.7). Every
case below must reproduce its recorded outcome exactly; the few outcomes that changed on purpose are
listed in :data:`DELIBERATE_DIFFERENCES` and asserted explicitly, with their new values, at the end of this module.

Regenerate (only ever against the code the fixture is meant to describe):
``uv run python -m tests.test_base_client_config_golden``.
"""

import functools
import json
import re
import warnings
from dataclasses import (
    fields,
    is_dataclass,
)
from pathlib import Path
from typing import (
    Any,
    Callable,
    Dict,
    FrozenSet,
)

import pytest

from ondewo.utils.base_client_config import BaseClientConfig
from tests.conftest import (
    PEM,
    REFRESH_TOKEN,
    SECRET,
    Inner,
    KeycloakConfig,
    NestedConfig,
    PipeUnionConfig,
)

GOLDEN_PATH: Path = Path(__file__).resolve().parent / "fixtures" / "base_client_config_golden.json"


def _describe(value: Any) -> Any:
    """
    Render a result as JSON-compatible data that pins its type and every field's ``repr``.

    Args:
        value (Any):
            A config, a nested dataclass, or a plain value.

    Returns:
        Any:
            ``{"type": ..., "fields": {...}}`` for a dataclass, ``value`` otherwise.
    """
    if is_dataclass(value) and not isinstance(value, type):
        return {
            "type": type(value).__name__,
            "fields": {config_field.name: repr(getattr(value, config_field.name)) for config_field in fields(value)},
        }
    return value


def _outcome(produce: Callable[[], Any]) -> Dict[str, Any]:
    """
    Run one case and record its result (or exception type) and any warnings it emitted.

    Args:
        produce (Callable[[], Any]):
            The case.

    Returns:
        Dict[str, Any]:
            ``{"result": ...}`` or ``{"error": <exception class name>}``, plus ``"warnings"``.
    """
    outcome: Dict[str, Any] = {}
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        try:
            outcome["result"] = _describe(produce())
        except Exception as error:
            outcome["error"] = type(error).__name__
    outcome["warnings"] = [f"{w.category.__name__}: {w.message}" for w in caught]
    return outcome


# Typed as Any so the cases type-check against both implementations (dataclasses-json injected the
# helpers at runtime, invisibly to mypy).
_PLAIN: Any = BaseClientConfig
_KEYCLOAK: Any = KeycloakConfig
_PIPE: Any = PipeUnionConfig
_NESTED: Any = NestedConfig

_BASE: Dict[str, Callable[[], Any]] = {
    "none": lambda: BaseClientConfig(host="localhost", port="50051"),
    "str_cert": lambda: BaseClientConfig(host="localhost", port="50051", grpc_cert=PEM),
    "bytes_cert": lambda: _PLAIN(host="localhost", port="50051", grpc_cert=PEM.encode()),
    "empty_cert": lambda: BaseClientConfig(host="localhost", port="50051", grpc_cert=""),
    "non_ascii": lambda: BaseClientConfig(host="hôst-ü.example", port="50051", grpc_cert=PEM + 'é ✓ 漢\t"\\'),
    "long": lambda: BaseClientConfig(host="h" * 255, port="1", grpc_cert="A" * 8192),
    "int_port": lambda: _PLAIN(host="localhost", port=50051),
    "keycloak": lambda: KeycloakConfig(
        host="localhost",
        port="50055",
        grpc_cert=PEM,
        user_name="user@ondewo.com",
        password=SECRET,
        keycloak_url="https://kc/auth",
        realm="ondewo-ccai-platform",
        client_id="ondewo-nlu-cai-sdk-public",
        token_expiration_in_s=3600,
        keycloak_verify_ssl=False,
        refresh_token=REFRESH_TOKEN,
    ),
    "pipe_union": lambda: PipeUnionConfig(host="h", port="1", realm="r", password=SECRET),
    "nested": lambda: NestedConfig(
        host="h", port="1", inner=Inner(name="n", weight=3), tags=["a", "b"], labels={"k": "v"}
    ),
}


def _apply(run: Callable[[Any], Any], build: Callable[[], Any]) -> Any:
    """
    Apply one serialization operation to a freshly built config.

    Args:
        run (Callable[[Any], Any]):
            The operation.
        build (Callable[[], Any]):
            Builds the config.

    Returns:
        Any:
            What the operation returned.
    """
    return run(build())


def _encode_cases() -> Dict[str, Callable[[], Any]]:
    """
    Build the serialization cases: every representative config through every output form.

    Returns:
        Dict[str, Callable[[], Any]]:
            Case id -> case.
    """
    operations: Dict[str, Callable[[Any], Any]] = {
        "to_dict": lambda config: config.to_dict(),
        "to_dict_encode_json": lambda config: config.to_dict(encode_json=True),
        "to_json": lambda config: config.to_json(),
        "to_json_indent_sorted": lambda config: config.to_json(indent=2, sort_keys=True),
        "to_json_utf8": lambda config: config.to_json(ensure_ascii=False),
        "json_round_trip": lambda config: type(config).from_json(config.to_json()),
        "dict_round_trip": lambda config: type(config).from_dict(config.to_dict()),
    }
    return {
        f"{name}.{operation}": functools.partial(_apply, run, build)
        for name, build in _BASE.items()
        for operation, run in operations.items()
    }


_HP: Dict[str, Any] = {"host": "h", "port": "1"}


_DECODE_CASES: Dict[str, Callable[[], Any]] = {
    "from_dict.unknown_keys_ignored": lambda: _KEYCLOAK.from_dict(
        {**_HP, "user_name": "u", "added_in_a_newer_client": 1, "nested": {"x": 1}}
    ),
    "from_dict.missing_optional_keys_default": lambda: _KEYCLOAK.from_dict(_HP),
    "from_dict.missing_mandatory_key": lambda: _PLAIN.from_dict({"port": "1"}),
    "from_dict.int_port_coerced": lambda: _PLAIN.from_dict({"host": "h", "port": 50051}),
    "from_dict.float_into_optional_int": lambda: _KEYCLOAK.from_dict({**_HP, "token_expiration_in_s": 7.9}),
    "from_dict.str_into_optional_int": lambda: _KEYCLOAK.from_dict({**_HP, "token_expiration_in_s": "30"}),
    "from_dict.bad_str_into_optional_int": lambda: _KEYCLOAK.from_dict({**_HP, "token_expiration_in_s": "x"}),
    "from_dict.str_false_into_bool": lambda: _KEYCLOAK.from_dict({**_HP, "keycloak_verify_ssl": "false"}),
    "from_dict.zero_into_bool": lambda: _KEYCLOAK.from_dict({**_HP, "keycloak_verify_ssl": 0}),
    "from_dict.int_into_str": lambda: _KEYCLOAK.from_dict({**_HP, "password": 1234}),
    "from_dict.list_into_str": lambda: _KEYCLOAK.from_dict({**_HP, "realm": ["a"]}),
    "from_dict.none_into_non_optional": lambda: _PLAIN.from_dict({"host": None, "port": "1"}),
    "from_dict.none_into_optional": lambda: _KEYCLOAK.from_dict({**_HP, "token_expiration_in_s": None}),
    "from_dict.empty_strings": lambda: _KEYCLOAK.from_dict({"host": "", "port": "", "grpc_cert": ""}),
    "from_dict.infer_missing": lambda: _PLAIN.from_dict({}, infer_missing=True),
    "from_dict.infer_missing_none": lambda: _PLAIN.from_dict(None, infer_missing=True),
    "from_dict.none": lambda: _PLAIN.from_dict(None),
    "from_dict.instance_passes_through": lambda: _PLAIN.from_dict(BaseClientConfig("h", "1")),
    "from_dict.bytes_cert": lambda: _PLAIN.from_dict({**_HP, "grpc_cert": b"PEM"}),
    "from_dict.pipe_union_coerces": lambda: _PIPE.from_dict({**_HP, "realm": 5, "token_expiration_in_s": "9"}),
    "from_dict.nested_from_mapping": lambda: _NESTED.from_dict(
        {**_HP, "inner": {"name": "n", "weight": "4", "unknown": 1}, "tags": ["t"], "labels": {"a": "b"}}
    ),
    "from_dict.nested_instance": lambda: _NESTED.from_dict({**_HP, "inner": Inner(name="n")}),
    "from_dict.nested_missing_mandatory": lambda: _NESTED.from_dict({**_HP, "inner": {"weight": 2}}),
    "from_json.bytes_input": lambda: _PLAIN.from_json(b'{"host": "h", "port": "1"}'),
    "from_json.escaped_unicode": lambda: _PLAIN.from_json('{"host": "h\\u00f4st", "port": "1"}'),
    "from_json.raw_unicode": lambda: _PLAIN.from_json('{"host": "hôst", "port": "1"}'),
    "from_json.duplicate_keys_last_wins": lambda: _PLAIN.from_json('{"host": "a", "host": "b", "port": "1"}'),
    "from_json.unknown_keys_ignored": lambda: _KEYCLOAK.from_json('{"host": "h", "port": "1", "x": [1, {}]}'),
    "from_json.list_document": lambda: _PLAIN.from_json("[1]"),
    "from_json.string_document": lambda: _PLAIN.from_json('"h"'),
    "from_json.null_document": lambda: _PLAIN.from_json("null"),
    "from_json.invalid": lambda: _PLAIN.from_json('{"host": "h", '),
    "from_json.empty": lambda: _PLAIN.from_json(""),
    "from_json.nan_into_optional_int": lambda: _KEYCLOAK.from_json(
        '{"host": "h", "port": "1", "token_expiration_in_s": NaN}'
    ),
    "from_json.parse_int_kwarg": lambda: _KEYCLOAK.from_json(
        '{"host": "h", "port": "1", "token_expiration_in_s": 5}', parse_int=lambda text: int(text) * 2
    ),
}


def all_cases() -> Dict[str, Callable[[], Any]]:
    """
    Return every golden case.

    Returns:
        Dict[str, Callable[[], Any]]:
            Case id -> case.
    """
    return {**_encode_cases(), **_DECODE_CASES}


# Outcomes that changed on purpose when dataclasses-json was replaced. Each one is asserted
# explicitly, with its new value, in the region at the end of this module.
DELIBERATE_DIFFERENCES: FrozenSet[str] = frozenset(
    # to_json() without arguments is orjson's compact UTF-8 rendering of the same document.
    {f"{name}.to_json" for name in _BASE}
    | {
        # A missing mandatory field: TypeError (the constructor's own error) instead of KeyError.
        "from_dict.missing_mandatory_key",
        "from_dict.nested_missing_mandatory",
        # A document that is not an object: TypeError naming the class instead of AttributeError.
        "from_dict.none",
        "from_json.list_document",
        "from_json.string_document",
        "from_json.null_document",
        # bytes passed to from_dict for grpc_cert are kept, not turned into the text "b'PEM'".
        "from_dict.bytes_cert",
        # orjson rejects the non-standard NaN literal instead of feeding it to int().
        "from_json.nan_into_optional_int",
    }
)


def _golden() -> Dict[str, Any]:
    """
    Load the recorded outcomes.

    Returns:
        Dict[str, Any]:
            Case id -> outcome.
    """
    golden: Dict[str, Any] = json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))
    return golden


def test_the_fixture_covers_exactly_the_cases() -> None:
    """Verify every case has a recorded outcome and no outcome is orphaned."""
    assert set(_golden()) == set(all_cases())


#: Fields added after the fixture was recorded. Unset, they are the only difference to the dataclasses-json era,
#: so the comparison drops them; their own behaviour is pinned in test_base_client_config.py.
FIELDS_ADDED_SINCE_THE_FIXTURE: FrozenSet[str] = frozenset({"grpc_client_cert", "grpc_client_key"})
_UNSET_ADDED_FIELD_IN_JSON: "re.Pattern[str]" = re.compile(
    r',\s*"(?:' + "|".join(sorted(FIELDS_ADDED_SINCE_THE_FIXTURE)) + r')":\s*null'
)


def _without_unset_added_fields(value: Any) -> Any:
    """
    Remove the fields added since the fixture, wherever an outcome renders them unset.

    Args:
        value (Any):
            An outcome or a part of one: a dict, a list, a JSON document or a plain value.

    Returns:
        Any:
            The same value without ``grpc_client_cert`` / ``grpc_client_key`` entries that are ``None``,
            the repr ``"None"`` or JSON ``null``.
    """
    if isinstance(value, dict):
        return {
            key: _without_unset_added_fields(item)
            for key, item in value.items()
            if not (key in FIELDS_ADDED_SINCE_THE_FIXTURE and item in (None, "None"))
        }
    if isinstance(value, list):
        return [_without_unset_added_fields(item) for item in value]
    if isinstance(value, str):
        return _UNSET_ADDED_FIELD_IN_JSON.sub("", value)
    return value


@pytest.mark.parametrize("case_id", sorted(set(all_cases()) - DELIBERATE_DIFFERENCES))
def test_the_outcome_matches_dataclasses_json(case_id: str) -> None:
    """Verify the case reproduces what dataclasses-json produced, byte for byte, apart from unset new fields."""
    assert _without_unset_added_fields(_outcome(all_cases()[case_id])) == _golden()[case_id]


# region the outcomes that differ from dataclasses-json ON PURPOSE (DELIBERATE_DIFFERENCES)


@pytest.mark.parametrize("name", sorted(_BASE))
def test_to_json_is_the_same_document_rendered_compact_and_utf8(name: str) -> None:
    """Verify ``to_json()`` is exactly dataclasses-json's document with orjson's compact UTF-8 layout."""
    old: str = _golden()[f"{name}.to_json"]["result"]
    new: str = _without_unset_added_fields(all_cases()[f"{name}.to_json"]())
    assert new == json.dumps(json.loads(old), separators=(",", ":"), ensure_ascii=False)
    assert json.loads(new) == json.loads(old)
    assert list(json.loads(new)) == list(json.loads(old))  # same key order


@pytest.mark.parametrize("case_id", ["from_dict.missing_mandatory_key", "from_dict.nested_missing_mandatory"])
def test_a_missing_mandatory_field_raises_type_error_instead_of_key_error(case_id: str) -> None:
    """Verify an absent field without a default raises the constructor's ``TypeError`` (was ``KeyError``)."""
    assert _golden()[case_id]["error"] == "KeyError"
    with pytest.raises(TypeError, match="missing 1 required"):
        all_cases()[case_id]()


@pytest.mark.parametrize(
    "case_id, received",
    [
        ("from_dict.none", "NoneType"),
        ("from_json.list_document", "list"),
        ("from_json.string_document", "str"),
        ("from_json.null_document", "NoneType"),
    ],
)
def test_a_document_that_is_not_an_object_raises_type_error(case_id: str, received: str) -> None:
    """Verify a non-object document raises a ``TypeError`` naming the class (was ``AttributeError``)."""
    assert _golden()[case_id]["error"] == "AttributeError"
    with pytest.raises(TypeError, match=f"BaseClientConfig must be decoded from a JSON object .*not {received}$"):
        all_cases()[case_id]()


def test_bytes_given_for_the_certificate_are_kept() -> None:
    """Verify ``from_dict`` keeps ``bytes`` as the constructor does (dataclasses-json made them ``"b'PEM'"``)."""
    assert _golden()["from_dict.bytes_cert"]["result"]["fields"]["grpc_cert"] == repr(b"b'PEM'")
    restored: BaseClientConfig = BaseClientConfig.from_dict({"host": "h", "port": "1", "grpc_cert": b"PEM"})
    assert restored == BaseClientConfig(host="h", port="1", grpc_cert="PEM")


def test_nan_is_rejected_as_invalid_json() -> None:
    """Verify orjson rejects the non-standard ``NaN`` literal (dataclasses-json fed it to ``int()``)."""
    assert _golden()["from_json.nan_into_optional_int"]["error"] == "ValueError"
    with pytest.raises(json.JSONDecodeError):
        all_cases()["from_json.nan_into_optional_int"]()


# endregion


if __name__ == "__main__":
    GOLDEN_PATH.parent.mkdir(exist_ok=True)
    recorded: Dict[str, Any] = {case_id: _outcome(case) for case_id, case in all_cases().items()}
    GOLDEN_PATH.write_text(json.dumps(recorded, indent=4, sort_keys=True) + "\n", encoding="utf-8")
